# Auto-generated package reinstall script
pkg update && pkg upgrade -y

pkg install -y Listing...
pkg install -y apt/stable,now
pkg install -y autoconf/stable,now
pkg install -y automake/stable,now
pkg install -y bash/stable,now
pkg install -y bc/stable,now
pkg install -y bison/stable,now
pkg install -y brotli/stable,now
pkg install -y build-essential/stable,now
pkg install -y ca-certificates-java/stable,now
pkg install -y ca-certificates/stable,now
pkg install -y clamav/stable,now
pkg install -y clang/stable,now
pkg install -y cmake/stable,now
pkg install -y command-not-found/stable,now
pkg install -y coreutils/stable,now
pkg install -y curl/stable,now
pkg install -y dash/stable,now
pkg install -y debianutils/stable,now
pkg install -y diffutils/stable,now
pkg install -y dos2unix/stable,now
pkg install -y dpkg/stable,now
pkg install -y ed/stable,now
pkg install -y findutils/stable,now
pkg install -y flex/stable,now
pkg install -y freetype/stable,now
pkg install -y gawk/stable,now
pkg install -y gdbm/stable,now
pkg install -y giflib/stable,now
pkg install -y glib/stable,now
pkg install -y gperf/stable,now
pkg install -y gpgv/stable,now
pkg install -y grep/stable,now
pkg install -y gzip/stable,now
pkg install -y inetutils/stable,now
pkg install -y json-c/stable,now
pkg install -y jsoncpp/stable,now
pkg install -y less/stable,now
pkg install -y libandroid-posix-semaphore/stable,now
pkg install -y libandroid-selinux/stable,now
pkg install -y libandroid-shmem/stable,now
pkg install -y libarchive/stable,now
pkg install -y libassuan/stable,now
pkg install -y libbcprov-java/stable,now
pkg install -y libbz2/stable,now
pkg install -y libc++/stable,now
pkg install -y libcap-ng/stable,now
pkg install -y libcommons-lang3-java/stable,now
pkg install -y libcompiler-rt/stable,now
pkg install -y libcrypt/stable,now
pkg install -y libcurl/stable,now
pkg install -y libevent/stable,now
pkg install -y libexpat/stable,now
pkg install -y libffi/stable,now
pkg install -y libgcrypt/stable,now
pkg install -y libgmp/stable,now
pkg install -y libgnutls/stable,now
pkg install -y libgpg-error/stable,now
pkg install -y libiconv/stable,now
pkg install -y libidn2/stable,now
pkg install -y libjpeg-turbo/stable,now
pkg install -y libllvm/stable,now
pkg install -y libltdl/stable,now
pkg install -y liblua54/stable,now
pkg install -y liblzma/stable,now
pkg install -y libmd/stable,now
pkg install -y libmpfr/stable,now
pkg install -y libnettle/stable,now
pkg install -y libnghttp2/stable,now
pkg install -y libnghttp3/stable,now
pkg install -y libnpth/stable,now
pkg install -y libpcap/stable,now
pkg install -y libpng/stable,now
pkg install -y libsmartcols/stable,now
pkg install -y libsqlite/stable,now
pkg install -y libssh2/stable,now
pkg install -y libtool/stable,now
pkg install -y libunbound/stable,now
pkg install -y libunistring/stable,now
pkg install -y libuuid/stable,now
pkg install -y libuv/stable,now
pkg install -y libx11/stable,now
pkg install -y libxau/stable,now
pkg install -y libxcb/stable,now
pkg install -y libxdmcp/stable,now
pkg install -y libxext/stable,now
pkg install -y libxi/stable,now
pkg install -y libxml2/stable,now
pkg install -y libxrender/stable,now
pkg install -y libxtst/stable,now
pkg install -y littlecms/stable,now
pkg install -y lld/stable,now
pkg install -y llvm/stable,now
pkg install -y m4/stable,now
pkg install -y make/stable,now
pkg install -y nano/stable,now
pkg install -y ncurses-ui-libs/stable,now
pkg install -y ncurses/stable,now
pkg install -y ndk-sysroot/stable,now
pkg install -y net-tools/stable,now
pkg install -y nmap/stable,now
pkg install -y openjdk-21-x/stable,now
pkg install -y openjdk-21/stable,now
pkg install -y openssl/stable,now
pkg install -y patch/stable,now
pkg install -y pcre2/stable,now
pkg install -y pdftk/stable,now
pkg install -y perl/stable,now
pkg install -y pkg-config/stable,now
pkg install -y portaudio/stable,now
pkg install -y procps/stable,now
pkg install -y psmisc/stable,now
pkg install -y python-ensurepip-wheels/stable,now
pkg install -y python-pip/stable,now
pkg install -y python/stable,now
pkg install -y readline/stable,now
pkg install -y resolv-conf/stable,now
pkg install -y rhash/stable,now
pkg install -y sed/stable,now
pkg install -y tar/stable,now
pkg install -y termux-am/stable,now
pkg install -y termux-api/stable,now
pkg install -y termux-exec/stable,now
pkg install -y termux-keyring/stable,now
pkg install -y termux-licenses/stable,now
pkg install -y termux-tools/stable,now
pkg install -y unzip/stable,now
pkg install -y util-linux/stable,now
pkg install -y wget/stable,now
pkg install -y xxhash/stable,now
pkg install -y zlib/stable,now
pkg install -y zstd/stable,now
